### ISSUE TITLE
Can't download the database on ADP website

### ISSUE THREAD

**Issue by ambarion** [mahdihosseini/ADP#1]
Hello,

I noticed that the database on ADP Website is to be released and under Ethics Board Review. May I ask when I can download the database? I've already activated my account on the website. But I can't download the database for the reasons stated before. Or, there is any other way to get the database from the internet? 

With many thanks

**Comment by andreped** [comment]
@ambarion Same issue. I assume that you got access to the data within a few days after registering, as you closed this issue yourself?
